package com.chenming.test;

import junit.framework.TestCase;

public class ExceptionTest extends TestCase{

	public void testException_1() {
		
		try {
			int i = 3/0;
		}catch(Exception e) {
			e.printStackTrace();
			System.out.println("Exception...");
		}
		System.out.println("这里执行到了");
	}
	
}
